"""Add to Comment created_at

Revision ID: a51001b06b19
Revises: 4699cd10ab95
Create Date: 2021-07-14 10:58:12.692453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51001b06b19'
down_revision = '4699cd10ab95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('create_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'create_at')
    # ### end Alembic commands ###
